version: '2'
services:
  proxy_compile:
    image: "golang:1.7-alpine"
    environment:
      GOBIN: /go/src/github.com/mklimuk/api-proxy/dist
      HUSAR_VERSION: acceptance
    volumes:
      - .:/go/src/github.com/mklimuk/api-proxy
    command: sh -c "go install -v github.com/mklimuk/api-proxy"
